# Generated by Django 2.2.6 on 2020-01-20 17:06

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='banner_picture_2',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='resume_upload',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='round_cirlce_picture',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='website',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='height_field',
            field=models.IntegerField(blank=True, default=1200, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='resume_upload',
            field=models.FileField(default=django.utils.timezone.now, help_text='Please Upload Your Resume Otherwise Your Profile Will Not be Created', upload_to='profile_pics', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='round_cirlce_picture',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='profile_pics', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='width_field',
            field=models.IntegerField(blank=True, default=800, null=True),
        ),
    ]
